# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Deploy apk to artifactory"
  lane :deploy_artifact do
    artifactory(
      username: "build_user",
      password: "siren-maenad-pizzeria",
      endpoint: "https://na-artifact-01.na.audatex.com:8443/artifactory",
      file: "./app/build/ouputs/apk/debug/app-debug.apk",
      repo: "mobile_frontend",
      repo_path: "/android_test/",
      ssl_verify: false
    )
  end

end
